title : Shibuya.lisp
tagline: Site Tagline
author :
  name : Name Lastname
  email : shibuya.lisp@gmail.com
  github : shibuya-lisp
  twitter : shibuya_lisp
logo: /assets/img/logo.png
description: Shibuya.lispは渋谷周辺半径2万キロのLispコミュニティです
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
markdown: kramdown
